- name: COLORS
  hosts: ubuntu
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: "doh"
      become: yes
      become_user: root
      lineinfile:
        path: ~/.bashrc
        # The String to Search
        regexp: "#force_color_prompt=yes"
        # The String to Replace
        line: "force_color_prompt=yes"
        state: present
        backup: yes

    - name: "doh2"
      #become: yes
      become_user: root
      lineinfile:
        path: ~/.bashrc
        # The String to Search
        regexp: "#force_color_prompt=yes"
        # The String to Replace
        line: "force_color_prompt=yes"
        state: present
        backup: yes
