- hosts: ubuntu
  vars:
    ansible_host_key_checking: false

  become: yes
  tasks:
    - name: PLS UPDATE
      apt:
        update_cache: yes
        upgrade: "yes"
      register: apt_update_status

    - name: DELETE OLD SHIT
      apt:
        autoremove: yes
      when: apt_update_status.changed

      uri:
        url: "{{ ntfy_server }}/{{ ntfy_channel_update }}"
        method: POST
        follow_redirects: all
        body: "update complete 🐓"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ token }}"
