- hosts: ubuntu
  vars:
    ansible_host_key_checking: false

  become: yes
  tasks:
    - name: PLS UPDATE
      apt:
        update_cache: yes
        upgrade: "yes"
      register: apt_update_status

    - name: DELETE OLD SHIT
      apt:
        autoremove: yes
      when: apt_update_status.changed

    - name: Send ntfy update
      uri:
        url: "{{ ntfy_server }}{{ ntfy_channel_update }}"
        return_content: true
        method: POST
        body: "update complete  🐓"
        headers:
          x-ms-client-auth-token: "{{ token }}"
