- hosts: ubuntu
  vars:
    ansible_host_key_checking: false
  become: yes
  tasks:
  - name: PLS UPDATE THIS BRO
    apt:
      update_cache: yes
      upgrade: 'yes'
    register: apt_update_status

  - name: DELETE OLD SHIT
    apt:
      autoremove: yes

  - name: REBOOT.me
    reboot:
      post_reboot_delay: 300
    when: apt_update_status.changed
