- hosts: ubuntu
  vars:
    ansible_host_key_checking: false

  become: yes
  tasks:
    - name: PLS UPDATE
      apt:
        update_cache: yes
        upgrade: "yes"
      register: apt_update_status

    - name: DELETE OLD SHIT
      apt:
        autoremove: yes

    - name: REBOOT.me
      reboot:
        post_reboot_delay: 180
      when: apt_update_status.changed

    - name: Send ntfy update
      uri:
        url: "{{ ntfy_channel_update }}/{{ ntfy_server }}"
        method: POST
        body: "update complete  🐄"
        headers:
          Content-Type: application/json
          x-ms-client-auth-token: "{{ token }}"
